/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as AddressAddressRouteImport } from './routes/address.$address'
import { Route as SubmissionSequenceRouteImport } from './routes/submission.$sequence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressAddressRoute = AddressAddressRouteImport.update({
  id: '/address/$address',
  path: '/address/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionSequenceRoute = SubmissionSequenceRouteImport.update({
  id: '/submission/$sequence',
  path: '/submission/$sequence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/storage': typeof StorageRoute
  '/submissions': typeof SubmissionsRoute
  '/address/$address': typeof AddressAddressRoute
  '/submission/$sequence': typeof SubmissionSequenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/storage': typeof StorageRoute
  '/submissions': typeof SubmissionsRoute
  '/address/$address': typeof AddressAddressRoute
  '/submission/$sequence': typeof SubmissionSequenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/storage': typeof StorageRoute
  '/submissions': typeof SubmissionsRoute
  '/address/$address': typeof AddressAddressRoute
  '/submission/$sequence': typeof SubmissionSequenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/history'
    | '/storage'
    | '/submissions'
    | '/address/$address'
    | '/submission/$sequence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/history'
    | '/storage'
    | '/submissions'
    | '/address/$address'
    | '/submission/$sequence'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/history'
    | '/storage'
    | '/submissions'
    | '/address/$address'
    | '/submission/$sequence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HistoryRoute: typeof HistoryRoute
  StorageRoute: typeof StorageRoute
  SubmissionsRoute: typeof SubmissionsRoute
  AddressAddressRoute: typeof AddressAddressRoute
  SubmissionSequenceRoute: typeof SubmissionSequenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/$address': {
      id: '/address/$address'
      path: '/address/$address'
      fullPath: '/address/$address'
      preLoaderRoute: typeof AddressAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission/$sequence': {
      id: '/submission/$sequence'
      path: '/submission/$sequence'
      fullPath: '/submission/$sequence'
      preLoaderRoute: typeof SubmissionSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  HistoryRoute: HistoryRoute,
  StorageRoute: StorageRoute,
  SubmissionsRoute: SubmissionsRoute,
  AddressAddressRoute: AddressAddressRoute,
  SubmissionSequenceRoute: SubmissionSequenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
